apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.project }}-vault-sa
  namespace: {{ $.Values.project }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ $.Values.project }}-vault-auth
  namespace: {{ $.Values.project }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: app
    serviceAccount: {{ $.Values.project }}-vault-sa
