{{- range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $app.name }}-gh-webhook
  namespace: {{ $.Values.project }}
spec:
  eventBusName: {{ $.Values.project }}-ci-eventbus
  template:
    serviceAccountName: {{ $.Values.project }}-ci-workflow-sa
  service:
    ports:
      - port: 12000
        targetPort: 12000
        name: webhook
  github:
    {{ $app.name }}-trigger:
      repositories:
        - owner: {{ $app.git.owner }}
          names:
            - {{ $app.git.repo }}
      webhook:
        endpoint: /{{ $.Values.project }}-{{ $app.name }}
        port: "12000"
        method: POST
        url: https://webhook.injunweb.com
      events:
        - push
      apiToken:
        name: {{ $.Values.project }}-github-access-secret
        key: token
      insecure: false
      active: true
      contentType: json
{{- end }}
